### ISSUE TITLE
Cards keep disconnecting 

### ISSUE THREAD

**Issue by karalabe** [keycard-tech/keycard-installer-android#14]
I've tried this with both the original cards and the ones from devcon too, but no luck. The original cards just connect/disconnect like crazy, every couple seconds. The cards from devcon get to the point of installing the applet, then tag lost, card disconnected. I've tried tens of times, always fails at the same point.

**Comment by karalabe** [comment]
Ha, the 202 verison of the apk works. The readme contains an old one that fails for me.

**Comment by gravityblast** [comment]
thank you @karalabe, we should update the README, but I think we will close this repo in favour of https://github.com/status-im/keycard-cli
Depending on the phone and on the state of the card, the installation is really heavy and can put the card in a weird state. Using the keycard shell and a usb reader should be more stable.
